// <auto-generated />
using System;
using FlowForge.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowForge.Persistence.Migrations
{
    [DbContext(typeof(FlowForgeDbContext))]
    [Migration("20260410205912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowForge.Domain.Entities.ActionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .IsUnique()
                        .HasDatabaseName("IX_ActionDefinitions_ActionType");

                    b.ToTable("ActionDefinitions", (string)null);
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.ActionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ActionExecutions_Status");

                    b.HasIndex("WorkflowExecutionId")
                        .HasDatabaseName("IX_ActionExecutions_WorkflowExecutionId");

                    b.HasIndex("WorkflowStepId")
                        .HasDatabaseName("IX_ActionExecutions_WorkflowStepId");

                    b.ToTable("ActionExecutions", (string)null);
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WorkflowExecutions_Status");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_WorkflowExecutions_WorkflowId");

                    b.ToTable("WorkflowExecutions", (string)null);
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActionDefinitionId")
                        .HasDatabaseName("IX_WorkflowSteps_ActionDefinitionId");

                    b.HasIndex("WorkflowId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowSteps_WorkflowId_Order");

                    b.ToTable("WorkflowSteps", (string)null);
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WorkflowTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_WorkflowTriggers_WorkflowId");

                    b.HasIndex("EventName", "SourceSystem")
                        .HasDatabaseName("IX_WorkflowTriggers_EventName_SourceSystem");

                    b.ToTable("WorkflowTriggers", (string)null);
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.ActionExecution", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.WorkflowExecution", "WorkflowExecution")
                        .WithMany("ActionExecutions")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowForge.Domain.Entities.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowExecution");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WorkflowExecution", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.ActionDefinition", "ActionDefinition")
                        .WithMany()
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowForge.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionDefinition");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WorkflowTrigger", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Triggers")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WorkflowExecution", b =>
                {
                    b.Navigation("ActionExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
